/* =============================================================================
   PHILBRICK — INDIA MAP GENERATOR (one-off; committed for reproducibility)

   Builds data/indiaMap.ts (a compact SVG outline of India + the projection
   constants shared with the city markers) from DataMeet's india-composite
   boundary — the Survey-of-India-convention outline, matching the client's own
   "Our Domestic Business" artwork.

   Source: https://github.com/datameet/maps (Country/india-composite.geojson,
   CC-BY 4.0 DataMeet community maps).

   Usage:  node scripts/generateIndiaMap.mjs <path-to-india-composite.geojson>
   ========================================================================== */
import { readFileSync, writeFileSync } from "node:fs";

const SRC = process.argv[2];
if (!SRC) {
  console.error("usage: node scripts/generateIndiaMap.mjs <india-composite.geojson>");
  process.exit(1);
}
const gj = JSON.parse(readFileSync(SRC, "utf8"));

/* ---- collect rings from all features ---------------------------------- */
const rings = [];
const pushGeom = (g) => {
  if (!g) return;
  if (g.type === "Polygon") rings.push(...g.coordinates);
  else if (g.type === "MultiPolygon") g.coordinates.forEach((p) => rings.push(...p));
  else if (g.type === "GeometryCollection") g.geometries.forEach(pushGeom);
};
(gj.features ?? [gj]).forEach((f) => pushGeom(f.geometry ?? f));

/* mainland = ring with the largest bbox area (islands excluded — the client's
   reference artwork also omits them) */
const area = (r) => {
  let minX = 1e9, maxX = -1e9, minY = 1e9, maxY = -1e9;
  for (const [x, y] of r) {
    if (x < minX) minX = x; if (x > maxX) maxX = x;
    if (y < minY) minY = y; if (y > maxY) maxY = y;
  }
  return (maxX - minX) * (maxY - minY);
};
rings.sort((a, b) => area(b) - area(a));
const mainland = rings[0];
console.log(`rings: ${rings.length}, mainland points: ${mainland.length}`);

/* ---- Douglas-Peucker simplification ------------------------------------ */
function simplify(points, tol) {
  const sqTol = tol * tol;
  const sqSegDist = (p, a, b) => {
    let x = a[0], y = a[1], dx = b[0] - x, dy = b[1] - y;
    if (dx !== 0 || dy !== 0) {
      const t = ((p[0] - x) * dx + (p[1] - y) * dy) / (dx * dx + dy * dy);
      if (t > 1) { x = b[0]; y = b[1]; }
      else if (t > 0) { x += dx * t; y += dy * t; }
    }
    dx = p[0] - x; dy = p[1] - y;
    return dx * dx + dy * dy;
  };
  const keep = new Uint8Array(points.length);
  keep[0] = keep[points.length - 1] = 1;
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [first, last] = stack.pop();
    let maxD = 0, idx = -1;
    for (let i = first + 1; i < last; i++) {
      const d = sqSegDist(points[i], points[first], points[last]);
      if (d > maxD) { maxD = d; idx = i; }
    }
    if (maxD > sqTol && idx > 0) {
      keep[idx] = 1;
      stack.push([first, idx], [idx, last]);
    }
  }
  return points.filter((_, i) => keep[i]);
}

let tol = 0.02;
let simplified = simplify(mainland, tol);
while (simplified.length > 520) {
  tol *= 1.3;
  simplified = simplify(mainland, tol);
}
console.log(`simplified: ${simplified.length} points (tol ${tol.toFixed(3)}°)`);

/* ---- projection: equirectangular, x compressed by cos(mid-lat) ---------- */
let minLon = 1e9, maxLon = -1e9, minLat = 1e9, maxLat = -1e9;
for (const [lon, lat] of simplified) {
  if (lon < minLon) minLon = lon; if (lon > maxLon) maxLon = lon;
  if (lat < minLat) minLat = lat; if (lat > maxLat) maxLat = lat;
}
const midLat = (minLat + maxLat) / 2;
const XS = Math.cos((midLat * Math.PI) / 180);
const WIDTH = 640;
const scale = WIDTH / ((maxLon - minLon) * XS);
const HEIGHT = Math.round((maxLat - minLat) * scale);
const px = (lon) => +(((lon - minLon) * XS) * scale).toFixed(1);
const py = (lat) => +(((maxLat - lat)) * scale).toFixed(1);

let d = "";
simplified.forEach(([lon, lat], i) => {
  d += (i === 0 ? "M" : "L") + px(lon) + " " + py(lat);
});
d += "Z";
console.log(`viewBox 0 0 ${WIDTH} ${HEIGHT}, path ${d.length} chars`);

const out = `/* =============================================================================
   INDIA MAP OUTLINE — generated by scripts/generateIndiaMap.mjs. Do not edit
   by hand; re-run the script to regenerate.

   Boundary: DataMeet india-composite (Survey-of-India convention, matching the
   client's own "Our Domestic Business" artwork), simplified to
   ${simplified.length} points. Islands omitted, as in the client's reference.
   Projection: equirectangular, x scaled by cos(${midLat.toFixed(2)}°).
   ========================================================================== */

export const INDIA_VIEW = { width: ${WIDTH}, height: ${HEIGHT} } as const;

/** Project a lon/lat pair into INDIA_VIEW coordinates (same projection the
 *  outline was generated with) — used to place the network city markers. */
export function projectIndia(lon: number, lat: number): { x: number; y: number } {
  const XS = ${XS.toFixed(6)};
  const SCALE = ${scale.toFixed(6)};
  return {
    x: (lon - ${minLon.toFixed(6)}) * XS * SCALE,
    y: (${maxLat.toFixed(6)} - lat) * SCALE,
  };
}

export const INDIA_PATH =
  "${d}";
`;
writeFileSync("data/indiaMap.ts", out);
console.log("wrote data/indiaMap.ts");
