/* =============================================================================
   PHILBRICK — PRODUCT CATALOGUE CONTENT (from the client's WordPress)

   PRODUCT_TREE (data/products.ts) owns the NAVIGATION: which categories exist,
   their order, and which products appear under them in the mega menu. This
   module owns the CONTENT for each product — the photography, the "Salient
   Features" lists and the specification tables — extracted verbatim from the
   client's WooCommerce database.

   Generated by  scripts/generateCatalog.mjs  ->  data/generated/catalog.json
   Re-run that script after any WordPress re-export; do not hand-edit the JSON.

   Content honesty (see CLAUDE.md): 19 of the 38 products carry no description
   on the client's live site. They are image-only here too — nothing is invented
   to fill the gap. Use `imageOnlyProducts()` to list them for the client.
   ========================================================================== */
import raw from "./generated/catalog.json";
import { PRODUCT_TREE } from "./products";

/** One "<h5>Salient Features:</h5><ul>…" block from the WordPress excerpt. */
export interface FeatureGroup {
  /** e.g. "Salient Features", or a sub-brand like "C-TOUCH - Salient Features". */
  heading: string;
  items: string[];
  /** Prose that sat outside the list, if any. */
  note?: string;
}

export interface CatalogProduct {
  slug: string;
  name: string;
  /** WordPress post ID — provenance, so a re-export can be reconciled. */
  wpId: string;
  /** Web paths under /images/products/catalog/, first is the primary shot. */
  images: string[];
  featureGroups: FeatureGroup[];
  /** Sanitised specification-table HTML. Empty when the client published none. */
  specHtml: string;
  hasContent: boolean;
}

export interface CatalogCategory {
  slug: string;
  products: CatalogProduct[];
}

export const CATALOG: CatalogCategory[] = (raw as { categories: CatalogCategory[] }).categories;

const BY_CATEGORY = new Map(CATALOG.map((c) => [c.slug, c]));
const BY_SLUG = new Map(CATALOG.flatMap((c) => c.products).map((p) => [p.slug, p]));

/** Every product the client published under a category, in nav order. */
export const categoryProducts = (categorySlug: string): CatalogProduct[] =>
  BY_CATEGORY.get(categorySlug)?.products ?? [];

export const getCatalogProduct = (slug: string): CatalogProduct | undefined =>
  BY_SLUG.get(slug);

/**
 * A category is "self-contained" when the client's navigation links straight to
 * it rather than to a submenu — Elevator Doors, COP/LOP, Elevator Cabin and so
 * on. Those landing pages show the product content inline instead of bouncing
 * the visitor through a one-item list.
 */
export const isSelfContained = (categorySlug: string): boolean =>
  !PRODUCT_TREE.find((c) => c.slug === categorySlug)?.children?.length;

/**
 * Primary card image for any tree node, preferring the client's real
 * photography over the AI-generated brand shots.
 *
 * Accepts a product slug OR a category slug: a category shows its first
 * product's lead photo, which is what the client's own category imagery is.
 * Falls back to the supplied brand image only when the catalogue has nothing —
 * so a node the client never photographed still renders something.
 */
export const productImage = (slug: string, fallback: string): string =>
  BY_SLUG.get(slug)?.images[0] ??
  BY_CATEGORY.get(slug)?.products[0]?.images[0] ??
  fallback;

/** Products the client has no copy for — hand this list back to them. */
export const imageOnlyProducts = (): CatalogProduct[] =>
  CATALOG.flatMap((c) => c.products).filter((p) => !p.hasContent);

/** Sibling products in the same category, for the "Related products" rail. */
export const relatedProducts = (
  categorySlug: string,
  productSlug: string
): CatalogProduct[] =>
  categoryProducts(categorySlug).filter((p) => p.slug !== productSlug);
