/* =============================================================================
   PART ASSETS — the photoreal imagery every hero variant is built around:
   the client's cutaway machine render (spine) and the 8 true-alpha component
   cutouts already shipped for /variant1. Served as the small WebP variants
   generated by scripts/optimizeHeroExploration.mjs (20 to 60 KB each).

   EVERY variant must showcase all 8 components (client requirement) — import
   PART_ASSETS and render the full set, with names from the single content
   source (data/elevatorComponents.ts).
   ========================================================================== */
import { ELEVATOR_COMPONENTS, type ElevatorComponent } from "@/data/elevatorComponents";

const A = "/images/home/hero-exploration/components";

export interface PartAsset {
  key: string;
  component: ElevatorComponent;
  /** exact WebP variant on disk (width-suffixed) */
  src: string;
  /** trimmed image width / height */
  aspect: number;
  /** 07 has a baked background — render it as a framed plate, not a cutout */
  framed?: boolean;
}

const SPECS: { key: string; src: string; aspect: number; framed?: boolean }[] = [
  { key: "motor", src: `${A}/01-traction-machine-640.webp`, aspect: 1.024 },
  { key: "key-switch", src: `${A}/02-security-key-switch-384.webp`, aspect: 0.7 },
  { key: "doors", src: `${A}/03-door-mechanism-640.webp`, aspect: 1.491 },
  { key: "control-panel", src: `${A}/04-car-operating-panel-295.webp`, aspect: 0.248 },
  { key: "safety", src: `${A}/05-safety-system-640.webp`, aspect: 0.608 },
  { key: "display", src: `${A}/06-display-screen-640.webp`, aspect: 1.414 },
  { key: "interior", src: `${A}/07-interior-design-640.webp`, aspect: 0.732, framed: true },
  { key: "emergency", src: `${A}/08-emergency-call-640.webp`, aspect: 0.881 },
];

export const PART_ASSETS: PartAsset[] = SPECS.map((s) => {
  const component = ELEVATOR_COMPONENTS.find((c) => c.key === s.key);
  if (!component) throw new Error(`partAssets: unknown component key "${s.key}"`);
  return { ...s, component };
});

/** the assembled machine cutaway (client render, feathered alpha edges) */
export const SPINE_ASSET = {
  src: "/images/home/hero-exploration/spine/elevator-cutaway-960.webp",
  aspect: 1024 / 1536,
};
