import type { IconType } from "react-icons";
import {
  FiActivity,
  FiAward,
  FiBarChart2,
  FiBox,
  FiBriefcase,
  FiCheckCircle,
  FiClock,
  FiCpu,
  FiDownload,
  FiGlobe,
  FiGrid,
  FiHeart,
  FiHome,
  FiLayers,
  FiLinkedin,
  FiInstagram,
  FiMail,
  FiMapPin,
  FiMonitor,
  FiPhone,
  FiRefreshCw,
  FiServer,
  FiSettings,
  FiShield,
  FiSmartphone,
  FiStar,
  FiSun,
  FiTool,
  FiTrendingUp,
  FiTruck,
  FiTwitter,
  FiUsers,
  FiWifi,
  FiYoutube,
  FiZap,
  FiFeather,
  FiNavigation,
  FiThermometer,
  FiEye,
  FiTarget,
  FiPackage,
} from "react-icons/fi";

/** Central icon registry — data files reference icons by string name. */
export const ICONS: Record<string, IconType> = {
  FiActivity,
  FiAward,
  FiBarChart2,
  FiBox,
  FiBriefcase,
  FiCheckCircle,
  FiClock,
  FiCpu,
  FiDownload,
  FiGlobe,
  FiGrid,
  FiHeart,
  FiHome,
  FiLayers,
  FiLinkedin,
  FiInstagram,
  FiMail,
  FiMapPin,
  FiMonitor,
  FiPhone,
  FiRefreshCw,
  FiServer,
  FiSettings,
  FiShield,
  FiSmartphone,
  FiStar,
  FiSun,
  FiTool,
  FiTrendingUp,
  FiTruck,
  FiTwitter,
  FiUsers,
  FiWifi,
  FiYoutube,
  FiZap,
  FiFeather,
  FiNavigation,
  FiThermometer,
  FiEye,
  FiTarget,
  FiPackage,
};

/** Resolve an icon by name, falling back to a neutral glyph. */
export function getIcon(name?: string): IconType {
  return (name && ICONS[name]) || FiBox;
}
